### ISSUE TITLE
Friendly_ids

### ISSUE THREAD

**Issue by javascriptisscary** [javascriptisscary/theerrorlogs#12]
Upon signing in user is redirected to users/:id/edit instead of users/:full_name/edit

**Comment by Adsidera** [comment]
it can be solved by adding, in the users_controller, (current_user.to_param) after the edit_user_path, to trigger the friendly_id slugs

`def show
    @user = User.friendly.find(params[:id])
    if @user == current_user
        redirect_to edit_user_path(current_user.to_param)`

**Comment by Adsidera** [comment]
This solution  is also making bundle exec rspec return 1 failure:
```
Failed examples:

rspec ./spec/controllers/users_controller_spec.rb:97 # UsersController User is logged in GET own #show page redirects to #edit
```

**Comment by Adsidera** [comment]
fixed :)
