### ISSUE TITLE
Devise Login or Signup links redirecting to wrong route

### ISSUE THREAD

**Issue by Adsidera** [javascriptisscary/theerrorlogs#21]
When clicking on the signup or login link (devise/shared/links) in the login or signup page, the wrong links are generated
For signup: user/sign_up.user - while signup link in the navbar is correctly redirecting to user/sign_up
For login: user/sign_in.user - while login link in the navbar is correctly redirecting to user/sign_in

**Comment by Adsidera** [comment]
it seems it can be fixed, by changing the routes.rb line starting with 'devise_for' in this way

devise_for :users, :controllers => { registrations: 'registrations' }, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'signup', :sign_out => 'logout'}

**Comment by javascriptisscary** [comment]
go for it ;)

**Comment by Adsidera** [comment]
Yes, I have seen that that line solves only partially this issue, though. 
It solves when you click on the link for signUP under the login form, but not when you click on the link for signIN in the signup form :)

**Comment by javascriptisscary** [comment]
Fixed, just waiting for the test update!

**Comment by Adsidera** [comment]
can you close it, Kenneth? The tests have been fixed meanwhile :)

**Comment by Adsidera** [comment]
closing issue :)
